---
title: "ANIMO efficacy outcome Tables"
author: "Kyle Humphrey"
date: "`r format(Sys.time(), '%B %d %Y')`"
output: html_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../results") })
editor_options: 
  chunk_output_type: console
---

```{r setup, echo = F, warning = F, message = F}
rm(list = ls())
knitr::opts_chunk$set(warning = F, echo = F, message = F)
library(pacman)
p_load(Hmisc, readxl, lme4, multcomp, tidyverse, broom, Gmisc)
select <- dplyr::select
```

```{r, eval = F}
# load data ---------------------------------------------------------------

var_names <- read_csv('../data/animo.csv', col_names = F, n_max = 1) %>%
  flatten_chr()
animo <- read.csv('../data/animo-labels.csv', header = F, skip = 1, stringsAsFactors = F) %>%
  set_names(var_names)
dxa <- read_excel('../data/Nosotros DXA Data Final KH.xlsx')
blood <- read.csv('../data/animo-blood.csv', stringsAsFactors = F)
food_base <- read.csv('../data/Animo_baselinesum2009r_sw.csv', stringsAsFactors = F)
food_week_12 <- read.csv('../data/Animo_12wksum2009r_sw.csv', stringsAsFactors = F)
food_week_24 <- read.csv('../data/Animo_24wsum2009r_sw.csv', stringsAsFactors = F)


# clean amino data --------------------------------------------------------

animo <- animo %>%
  group_by(participant_id) %>%
  mutate(group = group[1], # puts group assignment label in every observation
         age = age_esf[1]) %>% # puts age on every observation
  rowwise() %>%
  # change event names to weeks, and first event to week 0 (baseline)
  mutate(
    week = ifelse(
      redcap_event_name == 'Baseline',
      0,
      parse_number(redcap_event_name)
    ) %>% as.character()
  ) %>%
  select(-redcap_event_name)

# derive measurements (average of three taken at each assessment)
animo <- animo %>%
  rowwise() %>%
  mutate(weight_3_paf = as.numeric(weight_3_paf),
         weight_3_paf_mini = as.numeric(weight_3_paf_mini),
         weight = mean(c(weight_1_paf,
                         weight_2_paf,
                         weight_3_paf,
                         weight_1_paf_mini,
                         weight_2_paf_mini,
                         weight_3_paf_mini), na.rm = T),
         waist = mean(c(waist_1_paf, waist_2_paf, waist_3_paf), na.rm = T)
  ) %>% ungroup()

# subset to occasions and variables of interest
animo <- animo %>% filter(week %in% c(0, 12, 24), !is.na(group)) %>%
  select(participant_id, week, group, weight, waist, ends_with('gpaq'))


# clean physical activity data --------------------------------------------

animo <- animo %>%
  mutate_at(vars(starts_with("time")), funs(parse_number)) %>%
  mutate(
    vigorous_PA_minutes = days_vig_rec_gpaq *
      (time_vig_rec_h_gpaq * 60 + time_vig_rec_min_gpaq),
    vigorous_PA_minutes = ifelse(vig_rec_gpaq == "No",
                                 0,
                                 vigorous_PA_minutes),
    moderate_PA_minutes = days_mod_rec_gpaq *
      (time_mod_rec_h_gpaq * 60 + time_mod_rec_min_gpaq),
    moderate_PA_minutes = ifelse(mod_rec_gpaq == "No",
                                 0,
                                 vigorous_PA_minutes),
    total_PA_minutes = vigorous_PA_minutes + moderate_PA_minutes
  ) %>% select(-ends_with('gpaq'))


# clean food data ---------------------------------------------------------

food <- map2_df(
  list(food_base, food_week_12, food_week_24),
  c("0", "12", "24"),
  ~ .x %>% select(sid, kcals_per_day = ener) %>%
    mutate(sid = parse_number(sid),
           participant_id = ifelse(sid < 10,
                                   paste0("HMS3-00", sid),
                                   paste0("HMS3-0", sid)),
           week = .y) # %>% select(participant_id, week, kcals_per_day, -sid)
) %>% select(-sid)


# clean blood data --------------------------------------------------------

blood_labels <- tibble(
  hba1c = "Glycated.Hemoglobin",
  alt = "ALT",
  ast = "AST",
  cholesterol = "Cholesterol",
  hdl = "HDL.Cholesterol",
  ldl = "LDL.Cholesterol",
  triglycerides = "Triglycerides",
  hscrp = "hs.CRP"
)

variable_labels_blood  <- c(
  map_chr(blood_labels, ~ .x),
  map_chr(blood_labels, ~  paste0(.x, '.1')),
  map_chr(blood_labels, ~  paste0(.x, '.2'))
)

variable_names_blood <- c(
  names(blood_labels),
  paste0(names(blood_labels), '.1'),
  paste0(names(blood_labels), '.2')
)

# select variables of interest, set variable names
blood <- blood %>% select(Record.ID, one_of(variable_labels_blood)) %>%
  set_names(c('participant_id', variable_names_blood))

# fix wrong id
blood <- blood %>%
  mutate(participant_id = ifelse(participant_id == 'HMS-023',
                                 'HMS3-023',
                                 participant_id))

# select variables of interest, set variable names
blood <- blood %>%
  gather(key, value, -participant_id) %>%
  separate(key, c('var', 'week'), convert = T) %>%
  spread(key = var, value = value, convert = T)

# change weeks to be correct
blood <- blood %>%
  mutate(week = ifelse(is.na(week), 0, week),
         week = as.character(week * 12))

# reset lables to be pretty for output
blood_labels <- tibble(
  hba1c = "HbA1c",
  alt = "ALT",
  ast = "AST",
  cholesterol = "Total Cholesterol",
  hdl = "HDL Cholesterol",
  ldl = "LDL Cholesterol",
  triglycerides = "Triglycerides",
  hscrp = "hs-CRP"
)


# clean dxa data ----------------------------------------------------------

dxa <- dxa %>%
  rename(participant_id = patient_id,
         week = `time point`,
         pct_fat = TB_tissue_pfat) %>%
  mutate(week = as.character((week - 1) * 12))


# join all data -----------------------------------------------------------

animo <- full_join(animo, dxa, by = c("participant_id", "week")) %>%
  full_join(blood, by = c("participant_id", "week")) %>%
  full_join(food, by = c("participant_id", "week"))


# remove participants who weren’t randomized ------------------------------

animo <- animo %>%
  group_by(participant_id) %>%
  mutate(group = group[1]) %>%
  ungroup() %>%
  filter(!is.na(group))


# relabel groups ----------------------------------------------------------

animo <- animo %>%
  mutate(group = factor(group, 0:1, c("WLC", "GCSWLI")),
         week = factor(week, c(0, 12, 24)))


# save cleaned data -------------------------------------------------------

save(animo, file = "../data/animo-cleaned.Rdata")
```

```{r load cleaned data}
load("../data/animo-cleaned.Rdata")
```

```{r table functions}
get_glhts <- function(linfct, models_list, labels_df) {
  map(
    names(labels_df),
    ~ glht(models_list[[.x]], linfct)
  ) %>% set_names(names(labels_df))
}

missing_obs_df <- function(variable_name) {
  variable_name <- str_replace(variable_name, "log\\(", "") %>%
    str_replace("\\)", "") %>% str_replace("\\ \\+ 1", "")
  animo %>% group_by(group, week) %>%
    select(group, week, variable_name) %>%
    summarise_all(funs(missing = is.na(.) %>% sum(),
                       pct = (missing / length(.)) * 100)) %>%
    mutate(missing = paste0(missing,
                            " (", sprintf("%1.f",pct), ")")) %>%
    filter(!(group == "WLC" & week == 24)) %>%
    select(group, week, missing) %>%
    ungroup() %>%
    mutate_all(as.character) %>%
    mutate(group = paste0(group, "_missing")) %>%
    spread(key = week, value = missing)
}

get_results_df <- function(glht_obj, variable_name, difference = T,
                           sigfigs = 3, digits = NULL,
                           log_transformed = str_detect(variable_name, 'log')) {
  # returns a formatted data frame with 95% confidence intervals and p-values
  #   resulting from the contrasts given in a multcomp::glht object
  # inputs: glht_obj, a multcomp::glht object with contrasts of interest
  #         variable name, the variable name of interest

  ci_df <- confint(glht_obj, calpha = qnorm(.975)) %>%
    broom::tidy() %>% select(-rhs)

  if (log_transformed) {
    if (difference) {
      ci_df <- ci_df %>% mutate_at(vars(-lhs), funs((exp(.) - 1) * 100))
    } else if (str_detect(variable_name, '\\+ 1')) {
      ci_df <- ci_df %>% mutate_at(vars(-lhs), funs((exp(.) - 1)))
    } else {
      ci_df <- ci_df %>% mutate_at(vars(-lhs), funs(exp))
    }
  }

  if (difference) {
    pval_df <-
      summary(object = glht_obj, test = adjusted(type = "none")) %>%
      broom::tidy() %>%
      select(lhs, p.value)

    results_df <- full_join(ci_df, pval_df, by = 'lhs')
  } else {
    results_df <- ci_df
  }

  if (difference & log_transformed) {
    results_df <- results_df %>%
      mutate_at(vars(estimate, conf.low, conf.high),
                funs(sprintf("%.1f", .)))
  } else {
    results_df <- results_df %>%
      rowwise() %>%
      mutate_at(vars(estimate, conf.low, conf.high),
                funs(format(., digits = sigfigs, scientific = F, trim = T)))
  }

  results_df <- results_df %>%
    mutate(estimate = paste0(estimate,
                             " (", conf.low, ", ", conf.high, ")")) %>%
    select(-starts_with('conf'))

  if (difference) {
    results_df <- results_df %>%
      mutate(p.value = ifelse(p.value < 0.01,
                              "p < 0.01",
                              sprintf("p = %#.2g", p.value)),
             estimate = paste0(estimate, ", ", p.value)) %>%
      select(-p.value)
  }

  results_df <- results_df %>%
    separate(lhs, into = c("week", "group"), sep = "_") %>%
    spread(key = week, value = estimate)
  if (!difference) {
    results_df <- results_df %>%
      bind_rows(missing_obs_df(variable_name))
  }
  results_df <- results_df %>%
    mutate(variable = variable_name) %>%
    select(variable, everything()) %>%
    ungroup() %>%
    arrange(group)

  return(results_df)
}

get_results <- function(glht_list, difference = T, labels_df) {
  map2_df(glht_list, names(labels_df),
          ~ get_results_df(.x, .y, difference))
}


```

```{r contrasts}
linfct_means <- rbind(
  '0_WLC' = c(1, 0, 0, 0, 0, 0),
  '12_WLC' = c(1, 0, 1, 0, 0, 0),
  # '24_WLC' = c(1, 0, 0, 1, 0, 0),
  '0_GCSWLI' = c(1, 1, 0, 0, 0, 0),
  '12_GCSWLI' = c(1, 1, 1, 0, 1, 0),
  '24_GCSWLI' = c(1, 1, 0, 1, 0, 1)
)

linfct_diffs_base <- rbind(
  '12 - 0_WLC' = c(0, 0, 1, 0, 0, 0),
  # '24 - 0_WLC' = c(0, 0, 0, 1, 0, 0),
  '12 - 0_GCSWLI' = c(0, 0, 1, 0, 1, 0) #,
  # '24 - 0_GCSWLI' = c(0, 0, 0, 1, 0, 1)
)

linfct_diffs_grps <- rbind(
  # GCSWLI - WLC
  # "GCSWLI" after underscore in name to print on the GCSWLI line in the table
  '0_GCSWLI' = c(0, 1, 0, 0, 0, 0),
  '12_GCSWLI' = c(0, 0, 0, 0, 1, 0) #,
  # '24_GCSWLI - WLC' = c(0, 1, 0, 0, 0, 1)
)
```

```{r blood results}
# variable names and labels for table -------------------------------------

blood_labels <- tibble(
  hba1c = "HbA1c",
  alt = "ALT",
  ast = "AST",
  cholesterol = "Cholesterol",
  hdl = "HDL Cholesterol",
  ldl = "LDL Cholesterol",
  triglycerides = "Triglycerides",
  hscrp = "hs-CRP"
)


# log transform variables -------------------------------------------------

blood_labels <- blood_labels %>%
  rename_all(funs(paste0("log(", ., ")")))


# run models --------------------------------------------------------------

blood_models <- map(
  names(blood_labels),
  ~ lmer(
    as.formula(paste(.x, '~', 'group * week + (1 | participant_id)')),
    data = animo)
) %>% set_names(names(blood_labels))


# obtain contrasts of interest --------------------------------------------

blood_glhts <- map(
  list(linfct_means, linfct_diffs_base, linfct_diffs_grps),
  ~ get_glhts(.x, blood_models, blood_labels)
) %>% set_names('means', 'diffs_base', 'diffs_grps')


# get confidence intervals, and p-values in table form --------------------

blood_results <- map2(blood_glhts, c(F, T, T),
                      ~ get_results(.x, .y, blood_labels)) %>%
  set_names('means', 'diffs_base', 'diffs_grps')

```

```{r cardiometabolic table}
blood_results$means %>%
  full_join(blood_results$diffs_base, by = c("variable", "group")) %>%
  full_join(blood_results$diffs_grps, by = c("variable", "group")) %>%
  select(-variable, -group) %>%
  as.matrix() %>%
  `colnames<-`(c(
    "Baseline",
    "Week 12",
    "Week 24",
    "Week 12 - Baseline",
    "Baseline",
    "Week 12<sup>a</sup>"
  )) %>% 
  htmlTable(
    rnames = rep(c("GCSWLI", "Missing (%)", "WLC", "Missing (%)"), nrow(.)/4),
    rgroup = blood_labels %>% flatten_chr() %>% rep(4),
    n.rgroup = rep(4, nrow(.) / 4),
    cgroup = c("Mean assessments", "Percent change from baseline",
               "Percent differences between groups"),
    n.cgroup = c(3, 1, 2),
    caption = "Table XX: Cardiometabolic measures.",
    tfoot = "<sup>a</sup> Difference in change from baseline between groups at week 12"
  )
```

```{r macro measures variables and labels}
macro_labels <- tibble(
  weight = "Weight (kg)",
  `log(weight)` = "Percent weight change",
  waist = "Waist circumference (cm)",
  pct_fat = "Percent body fat",
  `log(total_PA_minutes + 1)` = "LTPA<sup>a</sup> (minutes/week)",
  kcals_per_day = "Average caloric intake (kcal/day)"
)
```

```{r macro models}
# models ------------------------------------------------------------------

macro_models <- map(
  names(macro_labels),
  ~ lmer(
    as.formula(paste(.x, '~', 'group * week + (1 | participant_id)')),
    data = animo %>% filter(!is.na(.x)))
) %>% set_names(names(macro_labels))


# contrasts ---------------------------------------------------------------

macro_glhts <- map(
  list(linfct_means, linfct_diffs_base, linfct_diffs_grps),
  ~ get_glhts(.x, macro_models, macro_labels)
) %>% set_names('means', 'diffs_base', 'diffs_grps')


# results -----------------------------------------------------------------

macro_results <- map2(macro_glhts, c(F, T, T),
                      ~ get_results(.x, .y, macro_labels)) %>%
  set_names('means', 'diffs_base', 'diffs_grps')


```

```{r macro mean table}
macro_results$means %>%
  # remove means of percent weight beacuse they're geo means 
  # not means of percent weight change
  mutate(`0` = ifelse(variable == "log(weight)", NA, `0`),
         `12` = ifelse(variable == "log(weight)", NA, `12`),
         `24` = ifelse(variable == "log(weight)", NA, `24`),) %>% 
  full_join(macro_results$diffs_base, by = c("variable", "group")) %>%
  full_join(macro_results$diffs_grps, by = c("variable", "group")) %>%
  select(-variable, -group) %>%
  as.matrix() %>%
  `colnames<-`(c(
    "Baseline",
    "Week 12",
    "Week 24",
    "Week 12 - Baseline",
    "Baseline",
    "Week 12<sup>b</sup>"
  )) %>% 
  htmlTable(
    rnames = rep(c("GCSWLI", "Missing (%)", "WLC", "Missing (%)"), nrow(.)/4),
    rgroup = macro_labels %>% flatten_chr() %>% rep(4),
    n.rgroup = rep(4, nrow(.) / 4),
    cgroup = c("Mean assessments", "Change from baseline",
               "Differences between groups"),
    n.cgroup = c(3, 1, 2),
    caption = "Table XX: measures.",
    tfoot = "<sup>a</sup> Lesiure time physical activity. Means given are geometric means, differences are percent differences.\n<sup>b</sup>Difference in change from baseline between groups at week 12"
  )
```
